import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "fuse - Đăng nhập",
  description: "Generated by create next app",
  icons: "/fuse.svg",
};

export default function SignInPage() {
  return <div>sign in</div>;
}
