import UserProfileModule from "@/components/modules/UserProfileModule";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "fuse - latest",
  description: "Generated by create next app",
  icons: "/fuse.svg",
};

export default function StudyAreaPage() {
  return <UserProfileModule></UserProfileModule>;
}
