import SettingAccountPage from "@/components/modules/SettingModule/SettingAccountPage";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "fuse - latest",
  description: "Generated by create next app",
  icons: "/fuse.svg",
};

export default function EditPage() {
  return <SettingAccountPage></SettingAccountPage>;
}
