import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "fuse - Đăng ký",
  description: "Generated by create next app",
  icons: "/fuse.svg",
};

export default function SignUpPage() {
  return <div>sign up</div>;
}
