import type { Metadata } from "next";

import SignInModule from "@/components/modules/SignInModule";

export const metadata: Metadata = {
  title: "fuse - Đăng ký",
  description: "Generated by create next app",
  icons: "/fuse.svg",
};

export default function SignUpPage() {
  return <SignInModule pageMode={"SIGNUP"} />;
}
