import { TIME_FORMAT } from "./formatDateTime";

const API_SERVER = process.env.NEXT_PUBLIC_API_SERVER;
const API_SERVER_SOCKET = process?.env?.NEXT_PUBLIC_SERVER_SOCKET_URL;
const ASSETS_URL = process.env.NEXT_PUBLIC_ASSETS_URL;
const SITE_URL = "/";

const FIREBASE_API_KEY = process.env.NEXT_PUBLIC_FIREBASE_API_KEY;
const FIREBASE_AUTH_DOMAIN = process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN;
const FIREBASE_PROJECT_ID = process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID;
const FIREBASE_MESSAGING_SENDER_ID =
  process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID;
const FIREBASE_APP_ID = process.env.NEXT_PUBLIC_FIREBASE_APP_ID;
const FIREBASE_MEASUREMENT_ID = process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID;
const FIREBASE_STORAGE_BUCKET = process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET;
const FIREBASE_KEY_PAIR = process.env.NEXT_PUBLIC_FIREBASE_KEY_PAIR;

const USER_INFO = "_user_info";
const ACCESS_TOKEN = "_access_token";
const REFRESH_TOKEN = "_refresh_token";
const IS_AUTH = "_is_auth";

const MAX_SUB_ACCOUNT = 4;

const SUB_ACCOUNT_ID = "_sub_account_id";
const SUB_ACCOUNT_INFO = "_sub_account_info";

const SCRIPT_JITSI = "https://meet.jit.si/external_api.js";

const constants = {
  API_SERVER,
  ASSETS_URL,
  SITE_URL,
  USER_INFO,
  ACCESS_TOKEN,
  REFRESH_TOKEN,
  IS_AUTH,
  MAX_SUB_ACCOUNT,
  SUB_ACCOUNT_ID,
  SUB_ACCOUNT_INFO,
  TIME_FORMAT,
  SCRIPT_JITSI,
  API_SERVER_SOCKET,
  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID,
  FIREBASE_MEASUREMENT_ID,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_KEY_PAIR,
};

export default constants;
